[package]
name = "example"
version = "0.1.0"
authors = ["François Mockers <mockersf@gmail.com>"]

[dependencies]
serde = "*"
serde_derive = "*"
serde_dynamodb = { git = "https://github.com/mockersf/serde_dynamodb" }

rusoto_core = "*"
rusoto_dynamodb = "*"

uuid = { version = "0.5", features = ["serde", "v4"] }
