language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - rust: stable
      env: RUSTFMT
      before_script:
        - rustup component add rustfmt
      script:
        - cargo fmt -- --check
    - rust: stable
      env: CLIPPY
      install:
        - rustup component add clippy
      script:
        - cargo clippy

cache: cargo

before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"

after_success:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_PULL_REQUEST" = "false" && "$TRAVIS_BRANCH" == "master" && "$TRAVIS_RUST_VERSION" == "beta" ]]; then
      cd serde_dynamodb && 
      cargo doc --no-deps --features rusoto_dynamodbstreams &&
      echo "<meta http-equiv=refresh content=0;url=serde_dynamodb/index.html>" > ../target/doc/index.html &&
      git clone https://github.com/davisp/ghp-import.git &&
      ./ghp-import/ghp_import.py -n -p -f -m "Documentation upload" -r https://"$GH_TOKEN"@github.com/"$TRAVIS_REPO_SLUG.git" ../target/doc &&
      echo "Uploaded documentation"
    fi
