pre-release-commit-message="chore: version {{version}}"
post-release-commit-message="chore: start next development iteration {{next_version}}"
tag-prefix=""
tag-name="{{prefix}}{{version}}"
tag-message="chore: {{version}}"
dev-version-ext="dev"
