[package]
name = "serde_dynamodb"
version = "0.0.2"
authors = ["François Mockers <mockersf@gmail.com>"]

[dependencies]
serde = "1.0.32"
rusoto_dynamodb = "0.32"

[dev-dependencies]
serde_derive = "*"
